### ISSUE TITLE
Error when using with Bazel

### ISSUE THREAD

**Issue by cristifalcas** [remarkjs/remark-validate-links#51]
### Subject of the issue

When I'm trying to run this with nodejs 10 or 12, I get this error:

```
Error: Cannot find module './package.json'. Please verify that the package.json has a valid "main" entry
    at Function.module.constructor._resolveFilename (/home/cristifalcas/.cache/bazel/_bazel_cristifalcas/6b39ea2a9cf0428af321c3c86d3145b0/execroot/com_etsy_search/bazel-out/k8-fastbuild/bin/apps/docserver/check_links_require_patch.js:482:17)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (apps/docserver/node_modules/remark-cli/cli.js:8:11)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Object.<anonymous> (/home/cristifalcas/.cache/bazel/_bazel_cristifalcas/6b39ea2a9cf0428af321c3c86d3145b0/execroot/com_etsy_search/bazel-out/k8-fastbuild/bin/apps/docserver/check_links_loader.js:32:24)
```

### Your environment

*   **OS**: linux
*   **Packages**: 
*   **Env**: node 12.13, yarn 1.13

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

I'm using this file for remark-cli:
```
const fs = require('fs');
const path = require('path');

exports.settings = {};

exports.plugins = [
  [require('remark-validate-links'), 
      {
        "repository": "https://github.etsycorp.com/Engineering/Search",
      }
  ]
];
```

The latest version that works of nodejs is 8.

Can you update package.json and add a "main" entry?

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behaviour

What should happen?

### Actual behaviour

What happens instead?

**Comment by ChristianMurphy** [comment]
@cristifalcas are you by any chance running the remark-cli through bazel?
The node module resolver doesn't need a `main` entry if `index.js`, `index.json`, or `index.node` is provided (`remark-validate-links` provides an `index.js`).

Bazel changes the behavior of the loader, which may result in the issue you are seeing https://github.com/bazelbuild/rules_nodejs/blob/b10d230ff927736b88267998b17f501e71db0276/internal/node/require_patch.js#L203-L226

**Comment by cristifalcas** [comment]
Yes, I'm using Bazel. Can I fix this in any way?

**Comment by ChristianMurphy** [comment]
@cristifalcas how are you calling remark-cli?
Could you share the bazel file or npm script where it is called?

**Comment by cristifalcas** [comment]
It was a mistake on my part. The entry pont was wrong:
```
    entry_point = ":node_modules/remark-cli/cli.js",
```
instead of 
```
    entry_point = "@npm//:node_modules/remark-cli/cli.js",
```

Thank you.
